---
   - name: "Bootstraping | Groupe Node"
     hosts: prod 
     user: ansible 
     become: yes
     gather_facts: false

     pre_tasks:
       - block:
           - name: "Vérification de la connectivité"
             ping: ~
         rescue:
           - debug:
               msg: "Module ping: erreur"
           - raw: bash -c "test -f /usr/bin/python || (apt-get update && apt-get install python python3 -yqq) || (yum -y install python)"
             register: output
         always:
           - setup: ~
     roles:
       - bootstrap
       - requirement

   - name: "Web: installation et déploiement"
     hosts: web
     become: true
     user: ansible
     tags: ['WEB']

     roles:
       - webserver
